# -*- coding: utf-8 -*-
"""
make_fixture.py - build the committed golden fixture from a real stats dump.

    cargo run -p tga-cli --bin tga -- "N:\\telegram export\\UA KOLAB RUST" \
        --stats tmp.stats.json --out nul
    python tools/make_fixture.py tmp.stats.json \
        crates/tga-report/tests/fixture.stats.json

WHY THIS EXISTS
---------------
The fixture used to be hand-written, which meant every figure in it was a
number somebody made up and then made self-consistent by hand. Hour histograms
invented that way are flat and short-tailed, so the quantile ramp -- which
exists precisely because real chat activity is long-tailed -- was never
exercised by anything but a shape that could not have come out of a chat.

So it is generated from a real archive instead. What it must NOT be is a real
archive: `*.stats.json` is gitignored because a dump is verbatim history from
real people, and this file is committed.

WHAT IS SCRUBBED, AND WHAT IS NOT
---------------------------------
Scrubbed: every display name, @handle, peer key, and every scrap of message
text. Nothing that can identify a person survives, including in map *keys*,
which is where this kind of scrub usually leaks.

Kept: every number, every date, every topic name, every media kind, every
domain. Those are what the report renders and what a golden is for. Topic names
are properties of the group, not of a person, and one of them is non-ASCII,
which is a case the golden needs.

Then the awkward shapes are injected on top -- see INJECT below. A real archive
is realistic but tidy; the golden's job is to also carry the cases that break
renderers, and a healthy export contains none of them.
"""
import json, io, sys, collections

# Fields whose *value* is a person's display name. `names` is the one that is
# easy to miss: `churn.events[].names` and `renamed[].names` are lists of real
# people, and a `name`-only rule walks straight past both.
NAME_FIELDS = {
    "name", "names", "who", "top", "opened_by",
    "from_name", "to_name", "a_name", "b_name",
}
# Fields whose value is a peer key.
KEY_FIELDS = {"key", "a", "b", "from", "to", "target", "source"}
# Fields whose value is message text, which is never kept at all.
#
# `title` is deliberately absent: in a `Stats` every `title` is generated by
# this program -- "Most reacted to", "Night owl" -- and blanking them would
# strip the golden of the labels it exists to pin.
TEXT_FIELDS = {"text", "summary", "snippet"}


class Scrub:
    def __init__(self):
        self.names, self.keys, self.handles = {}, {}, {}

    def name(self, v):
        if not isinstance(v, str) or not v:
            return v
        if v not in self.names:
            self.names[v] = "Person %d" % (len(self.names) + 1)
        return self.names[v]

    def key(self, v):
        if not isinstance(v, str) or not v:
            return v
        if v not in self.keys:
            self.keys[v] = "user%d" % (len(self.keys) + 1)
        return self.keys[v]

    def handle(self, v):
        if not isinstance(v, str) or not v:
            return v
        if v not in self.handles:
            self.handles[v] = "handle_%d" % (len(self.handles) + 1)
        return self.handles[v]


# Paths whose `name` is NOT a person: the archive's own title and the topics.
#
# Written as a keep-list rather than an allow-list on purpose. Miss an entry
# here and something gets scrubbed that did not need to be, which is merely
# untidy; miss an entry on an allow-list and a real person's name ships in a
# committed file. The failure modes are not symmetric, so the default is scrub.
def keeps_its_name(path):
    return path in ("/export/name",) or (
        path.startswith("/topics[") and path.endswith("]/name")
    )


def walk(node, s, field=None, path=""):
    if isinstance(node, dict):
        return {k: walk(v, s, k, path + "/" + k) for k, v in node.items()}
    if isinstance(node, list):
        # `Count` is `["label", 41]`, and for emoji/domains the label is data,
        # not a name -- so lists are walked with the *parent* field name intact.
        return [walk(v, s, field, "%s[%d]" % (path, i)) for i, v in enumerate(node)]
    if isinstance(node, str):
        if field in NAME_FIELDS and not keeps_its_name(path):
            return s.name(node)
        if field in KEY_FIELDS:
            return s.key(node)
        if field == "username":
            return s.handle(node)
        if field in TEXT_FIELDS:
            return "(text removed)"
        if field == "aliases":
            return s.name(node)
    return node


def remap_keys(d, s, kind):
    """Maps keyed by peer key or by name leak through `walk`, which only sees
    values. Every one of them is remapped here by hand, because a scrub that
    misses a map key is a scrub that publishes the thing it was written to
    hide."""
    fn = s.key if kind == "key" else s.name
    return {fn(k): v for k, v in d.items()}


def main(src, dst):
    d = json.load(io.open(src, encoding="utf-8"))
    s = Scrub()

    # Names and keys first, so every later reference resolves to the same
    # stand-in. Rows are already sorted loudest-first.
    rows_in = d.get("people", {}).get("rows", [])
    for row in rows_in:
        s.name(row.get("name", ""))
        s.key(row.get("key", ""))

    # The loudest person gets a name that has to be escaped, and gets it *in the
    # name map* rather than by patching the table afterwards -- so the reply
    # matrix, the network diagram, the pair rows and the awards all call them
    # the same thing. Patching one table leaves the same human with two names in
    # one document, which is a worse fixture than having no awkward name at all.
    if rows_in:
        s.names[rows_in[0]["name"]] = "Bob & Co <the second>"

    out = walk(d, s, None)

    # -- the maps `walk` cannot reach -------------------------------------
    act = out.get("activity", {})
    if "per_day_by_person" in act:
        act["per_day_by_person"] = remap_keys(act["per_day_by_person"], s, "key")
    con = out.get("content", {})
    if "emoji_by_person" in con:
        con["emoji_by_person"] = remap_keys(con["emoji_by_person"], s, "key")
    # `mentions` are @handles of real people, dressed as a Count label.
    con["mentions"] = [["@" + s.handle(l.lstrip("@")), n]
                       for l, n in con.get("mentions", [])]
    # Forward sources are the names of people and channels the group quoted.
    con["forward_sources"] = [[s.name(l), n] for l, n in con.get("forward_sources", [])]

    inject(out)

    json.dump(out, io.open(dst, "w", encoding="utf-8"), ensure_ascii=False,
              indent=1, sort_keys=True)
    print("wrote %s: %d names, %d keys, %d handles scrubbed"
          % (dst, len(s.names), len(s.keys), len(s.handles)))


def inject(out):
    """The shapes that break renderers, which a healthy archive does not have.

    A real export is realistic but tidy: everybody is a `member`, the roster is
    complete, and nobody has an ampersand in their name. Those are exactly the
    cases worth pinning, so they are put back deliberately -- and *here*, in one
    place with a reason attached, rather than smuggled into a hand-maintained
    file where the next reader cannot tell which values are real."""
    people = out.setdefault("people", {})
    rows = people.get("rows", [])

    # 1. The escaped name is applied in the name map, before the walk -- see
    #    `main`. Nothing to do here.

    # 2. An alias list, so the "was ..." markup and its toggle are covered.
    for row in rows:
        if row.get("aliases"):
            break
    else:
        for row in rows:
            if row.get("messages", 0) > 0:
                row["aliases"] = ["Bobby", "B."]
                break

    # 3. A role that is not `member`. The exporter that wrote this archive's
    #    participants.json records no roles at all, so every row says `member`
    #    and the role markup would never render.
    for row in rows:
        if row.get("listed"):
            row["role"] = "creator"
            break

    # 4. A roster the export admits is short, and one it says it truncated.
    #    Both caveats are branches the real file (complete, uncapped) cannot
    #    reach, and they are the two the reader most needs to see.
    people["roster_complete"] = False
    people["roster_capped"] = True


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
